---
# tasks file for docker_compose

- name: import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: true
  delegate_to: localhost

- name: install docker-compose
  ansible.builtin.get_url:
    url: '{{ docker_compose_url }}'
    dest: /usr/local/bin/docker-compose
    mode: '0755'
