---
# tasks file for docker

- name: install require packages
  ansible.builtin.package:
    name: '{{ docker_ce_requirements }}'
    state: present
  when:
    - docker_ce_requirements | length

- name: install docker-ce repository for yum
  ansible.builtin.get_url:
    url: '{{ docker_ce_yum_repositories }}'
    dest: /etc/yum.repos.d/docker-ce.repo
  when:
    - ansible_pkg_mgr in [ 'yum' ]

- name: install docker-ce packages
  ansible.builtin.package:
    name: '{{ docker_ce_packages }}'
    state: present

- name: start and enable docker-ce
  ansible.builtin.service:
    name: '{{ docker_ce_service }}'
    state: started
    enabled: true
