---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: docker
platforms:
  - name: httpd-centos
    image: docker.io/pycontribs/centos:7
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
