---
# handlers file for ntp

- name: restart ntp
  ansible.builtin.service:
    name: '{{ ntp_serivce }}'
    state: restarted
  when:
    - not ansible_check_mode | bool
    - ntp_state == 'started'
