---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: install a package
      ansible.builtin.package:
        name: w3m
        state: present
